// clayj_web/src/components/ContentItem.vue
<template>
  <div class="item">
    <i>
      <slot name="icon"></slot>
    </i>
    <div class="details">
      <h2 class="heading">
        <slot name="heading"></slot>
      </h2>
      <slot></slot>
    </div>
  </div>
</template>

<style scoped>
.item {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding-right: 30px;
  padding-left: 30px;
  border-left: 1px solid;
  height: 100%;
  padding-top: 30px;
  padding-bottom: 30px;
}

.heading {
  font-weight: bold;
}

.item:first-of-type {
  border-left: 0px;
}

.details {
  display: flex;
  flex-direction: column;
  align-items: center;
  max-width: 400px;
}
</style>

// clayj_web/src/components/ContentItem.svelte
<div class="flex flex-col gap-1">
    <div class="flex justify-center">
        <h2 class="text-2xl font-bold flex-grow-0 py-1 max-w-fit border-b-2 border-slate-200">
            <slot name="heading"></slot>
        </h2>
    </div>
    <div class="text-center">
        <slot name="content"></slot>
    </div>
</div>
